[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_LIVE_URL = "https://pit-wall-f1-project-live.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
